name: "Xcode Create Simulator"
description: "Creates an simulator specific version"
inputs:
  device:
    description: "e.g. [iPhone 8, iPhone 11 Pro Max]"
    required: true
  runtime:
    description: "Version specifier"
    required: true

outputs:
  uuid:
    value: ${{ steps.create.outputs.uuid }}
runs:
  using: "composite"
  steps:
    - name: List Runtimes
      shell: bash
      run: |
        xcrun simctl list runtimes
    - name: List Devices
      shell: bash
      run: |
        xcrun simctl list devices
    - name: Format
      id: format
      uses: actions/github-script@v6
      with:
        script: |
          core.setOutput("device", "${{ inputs.device }}".replace(/\s/g, "-"))
          core.setOutput("runtime", "${{ inputs.runtime }}".replace(/\./g, "-"))
    - name: Create
      id: create
      shell: bash
      run: |
        UUID=$(xcrun simctl create SIM com.apple.CoreSimulator.SimDeviceType.${{ steps.format.outputs.device }} com.apple.CoreSimulator.SimRuntime.iOS-${{ steps.format.outputs.runtime }})
        echo "uuid=$UUID" >> $GITHUB_OUTPUT
